package org.igutech.auto;

public enum State {
    PREPARE_TO_SHOOT,
    SHOOTING_PRELOAD_RINGS,
    INTAKE_RING_STACK,
    DROP_FIRST_WOBBLE_GOAL,
    MOVE_TO_SHOOT_RING_STACK,
    SHOOTING_RING_STACK,
    MOVE_TO_GRAB_SECOND_GOAL,
    DROP_SECOND_GOAL,
    OFF
}
